Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style:
  Enabled: false

Metrics:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/ElseAl:
  Enabled: false

Naming:
  Enabled: false

# Metrics/AbcSize:
#   Enabled: false

# Metrics/MethodLength:
#   Enabled: false
