Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

# Metrics/AbcSize:
#   Enabled: false

# Metrics/MethodLength:
#   Enabled: false
